--
-- PostgreSQL database dump
--

\restrict psUgWCdIwuaff5NvKTLA0cxXOCCgdkMhU5ybgXEkH4oVaThVvM9go4JD9sNrKiJ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id integer NOT NULL,
    cat text
);


ALTER TABLE public.category OWNER TO postgres;

--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: height; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.height (
    id integer NOT NULL,
    cm integer
);


ALTER TABLE public.height OWNER TO postgres;

--
-- Name: height_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.height ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.height_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paintings; Type: TABLE; Schema: public; Owner: maemo
--

CREATE TABLE public.paintings (
    id uuid NOT NULL,
    height_id integer,
    width_id integer,
    category_id integer,
    name text,
    image_link text,
    price numeric(10,2),
    sold boolean
);


ALTER TABLE public.paintings OWNER TO maemo;

--
-- Name: width; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.width (
    id integer NOT NULL,
    cm integer
);


ALTER TABLE public.width OWNER TO postgres;

--
-- Name: width_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.width ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.width_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260119082043_InitialCreate	9.0.4
20260309120203_DbChanges	9.0.4
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category (id, cat) FROM stdin;
1	Cute animals
2	Fairytales
3	Animal planet
4	Flowers
\.


--
-- Data for Name: height; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.height (id, cm) FROM stdin;
2	50
3	120
4	90
5	15
6	100
7	30
8	40
9	20
10	25
11	18
12	60
13	70
14	80
15	26
\.


--
-- Data for Name: paintings; Type: TABLE DATA; Schema: public; Owner: maemo
--

COPY public.paintings (id, height_id, width_id, category_id, name, image_link, price, sold) FROM stdin;
cf471600-20b8-4475-9418-310002ec77af	2	2	1	Three comrades	3-comrades	794.00	f
50fe2911-638b-4cb9-b39d-8b1621c824dc	5	5	1	Hamster romantic - 1	ham-romantic-1	500.00	t
577ed99d-1822-4e0d-8066-8b8c5578698d	5	5	1	Hamster romantic - 2	ham-romantic-2	500.00	t
154e0063-eef7-4de6-8c32-366f500abaa8	6	6	1	The sea inside you - 1	sea-inside-1	500.00	t
fa212975-e2dd-4059-892b-1e2b30588b72	6	6	1	The sea inside you - 2	sea-inside-2	500.00	t
e9745ac5-5f5b-456b-9fed-3e5852a128f4	7	7	1	Owls in love	owls-in-love	500.00	t
278dbc43-0e40-44a4-a690-e5e9b068ae5d	7	7	1	Owl in love	owl-in-love	500.00	t
3fd7bb7d-a0fe-441e-b20b-ce69cb281e96	8	7	1	Fox	fox	500.00	t
8392a02b-d7cb-4196-8ac3-8a56756f15b1	9	8	1	Rabbit	rabbit	500.00	t
9780c417-8042-4ca8-bbf9-43f1c9e25d1d	10	9	1	Little squirrel 1	lil-squirrel-1	500.00	t
d58799bd-55af-4187-b625-0725c30db3d0	10	9	1	Little squirrel 2	lil-squirrel-2	500.00	t
09ea495d-9198-4eed-ae11-65c3429bb1a1	10	9	1	Little owl	lil-owl	500.00	t
a55e8d30-2500-436d-88c5-7109281990ea	5	5	1	Baby bird	baby-bird	500.00	t
8143d3bb-5442-425b-b912-a6bd1ad0da91	11	10	1	On a date	on-a-date	500.00	t
cb5cd905-2827-4d4a-8469-60be31815a6a	12	11	2	Sleeping Beauty	sleeping-beauty	694.00	f
19dd8c31-9c37-4a2e-b44b-e9896c83fa39	6	12	2	Rampion	rampion	1501.00	f
ac55fdb9-add2-448f-9df1-0fd285629c5b	13	13	2	Naughty angel-1	naughty-angel-1	409.00	f
3e58c97f-1034-4868-9a4b-eb853926d6a8	13	13	2	Naughty angel-2	naughty-angel-2	409.00	f
1fd061ac-9fd5-4305-add9-f70bd37c0917	12	4	2	Angel of good dreams-1	angel-good-1	499.00	t
2f3c2b39-b7c2-4955-b4e0-4ad9a384d0ae	12	4	2	Angel of good dreams-2	angel-good-2	499.00	f
265e458d-2630-4e7e-b7b5-83ea14915ef9	14	6	2	The princess of dreams	princess-of-dreams	1499.00	f
a5ea8b2c-95ee-488a-8053-7b18d5226868	6	12	2	Undine	undine	1499.00	f
ce134d3f-dc63-442f-ac8f-8f8eaae233f4	14	3	2	Ligo	ligo	500.00	t
2cf462d9-6605-4f21-9e4e-89d3abdaabd3	10	9	2	Little star of wishes Marfusha	star-wishes-marfusha	161.00	f
0e44bbb5-c7a2-4ff5-87f0-df465e4fe189	10	9	2	Little star of wishes Agasha	star-wishes-agasha	161.00	t
103801cc-a5da-411d-a7c3-292ab05b407d	5	5	2	Little star of wishes Nyusha	star-wishes-nyusha	146.00	f
52b29c48-fd21-4d11-ab63-01dfa8241e33	10	14	3	Cupidog	cupidog	224.00	f
622aae2e-337a-4f66-88c2-c606cd2a8208	8	7	3	Sweet dreams	sweet-dreams	294.00	f
855daeb1-a802-464f-862b-3fc2e51af92b	10	14	3	Yoga	yoga	224.00	f
3dedd57f-0797-4261-93c6-9e01c5718634	8	7	3	Morning exercises	morning-exer	294.00	f
d5e89ebb-ce7f-4a45-8d62-6fc54212e338	7	7	3	Birthday's boy	birthday-boy	244.00	f
cb67974e-b80e-4550-85ae-cdd0601c7fdf	8	14	3	Nirvana	nirvana	294.00	f
56d5d294-87a4-478b-b3fd-5820c8f3ac99	15	15	3	Time for yourself	time-for-yourself	500.00	t
a373f61b-4d0c-4375-b1c3-c2ef69f8f88d	8	16	3	Shopping	shopping	294.00	f
ab25bb0e-7c07-450a-af86-872c974f70fc	8	16	3	Casanova	casanova	500.00	t
9dc2d2f1-c767-4ebe-b17e-f8c52bacdc5f	7	14	3	Dreams come true	dreams-come-true	500.00	t
36455de2-0848-41f9-84cd-e5adc7fb3519	7	14	3	Sweet tooth	sweet-tooth	500.00	t
57e47aa9-32bd-4326-b592-bfc095fdb350	15	15	3	Love is	love-is	500.00	t
1eeffd24-a99d-4b30-a301-cb63718e2aa4	8	7	3	Sensey	sensey	500.00	t
32663bf8-015f-4198-a0ad-a4639d93226a	10	7	3	Trip	trip	500.00	t
dafff00a-828a-426b-8dda-b751d76cf39d	14	4	3	Sweet dream	sweet-dream	500.00	t
8df74cae-5915-4010-a8fe-62b093f6326f	8	7	3	First cup of coffee	first-cup-coffee	500.00	t
c4c9d345-4d3c-4162-9f5c-5a42dcc3baa6	8	16	3	Vacation	vacation	500.00	t
9a94ecf6-2158-4eb4-a402-8297b20d99be	8	16	3	Morning	morning	500.00	t
b068a3bb-ab44-4e61-8ce6-ad7b01188050	8	16	4	Artichoke	artichoke	500.00	t
39f288ae-3e2f-4c9f-952d-9107e9a6e06a	2	13	4	Tulip 1	tulip-1	594.00	f
02f0163f-5629-4f0b-9c22-6c18d5213d91	8	16	4	Tulip 2	tulip-2	494.00	f
b45cf14c-8f59-4798-8abd-df4460276b8b	12	4	4	Tulip-3	tulip-3	794.00	f
7bf95156-af76-46e4-a347-2ca33b8d920a	13	13	4	Red amaryllis	red-amaryllis	794.00	f
f3fc238a-ed9e-4259-9665-07606f0a188e	4	4	1	Butterfly in one's stomach 	butterfly-stomach	684.00	f
1a0c2a1a-b634-4be3-b858-849f678da22f	13	2	4	Amaryllis	amaryllis	894.00	f
3232eb15-392b-4cbd-b152-bf146baf0dbd	13	13	4	The tulip in the wind	tulip-in-wind	401.00	f
40e5b70f-8a08-4fae-9e6d-3381fcdf1e01	13	17	4	The secret passion of an unknown bird-1	unknown-bird-1	500.00	t
cc0989fa-e88c-47b9-98ff-f0b59605f2d9	13	17	4	The secret passion of an unknown bird-2	unknown-bird-2	500.00	t
15ee622d-f384-4a73-8ea0-4da47f376a68	3	3	4	Tulips-1	tulips-1	500.00	t
5183d233-54d2-4b9f-80be-69109e8e5c65	3	3	4	Tulips-2	tulips-2	500.00	t
bad5b392-0e70-4a68-a83e-36c1eaba2ca3	8	16	4	Little tulip	little-tulip	244.00	f
6d850a8e-72d7-4c1e-982e-9dbed9aca3d3	14	4	4	Guzmania	guzmania	844.00	f
72fb3814-e873-4f2d-b952-9e44017add99	13	17	4	Poppies flowers	poppies-flowers	944.00	f
6580f93e-a131-4277-928c-b8d8edac1baf	12	4	4	Tulip	tulip	500.00	t
fe0732c7-4384-4240-ad3e-5e3d8c197346	4	11	4	Iris	iris	1394.00	f
d7126bef-1649-4b26-9f6e-d89f8125e248	7	7	4	Sunflower	sunflower	284.00	f
df4f2d75-2b0e-4848-852a-02c2a5c5ebb9	3	3	1	Yin Yang	yin-yang	1964.00	t
\.


--
-- Data for Name: width; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.width (id, cm) FROM stdin;
2	70
3	150
4	60
5	15
6	80
7	30
8	15
9	20
10	13
11	90
12	120
13	50
14	25
15	26
16	40
17	100
\.


--
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_id_seq', 1, true);


--
-- Name: height_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.height_id_seq', 15, true);


--
-- Name: width_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.width_id_seq', 17, true);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: category PK_category; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT "PK_category" PRIMARY KEY (id);


--
-- Name: height PK_height; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.height
    ADD CONSTRAINT "PK_height" PRIMARY KEY (id);


--
-- Name: width PK_width; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.width
    ADD CONSTRAINT "PK_width" PRIMARY KEY (id);


--
-- Name: paintings paintings_pkey; Type: CONSTRAINT; Schema: public; Owner: maemo
--

ALTER TABLE ONLY public.paintings
    ADD CONSTRAINT paintings_pkey PRIMARY KEY (id);


--
-- Name: IX_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_category_id" ON public.category USING btree (id);


--
-- Name: IX_paintings_height_id; Type: INDEX; Schema: public; Owner: maemo
--

CREATE INDEX "IX_paintings_height_id" ON public.paintings USING btree (height_id);


--
-- Name: IX_paintings_width_id; Type: INDEX; Schema: public; Owner: maemo
--

CREATE INDEX "IX_paintings_width_id" ON public.paintings USING btree (width_id);


--
-- Name: paintings paintings_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: maemo
--

ALTER TABLE ONLY public.paintings
    ADD CONSTRAINT paintings_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: paintings paintings_height_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: maemo
--

ALTER TABLE ONLY public.paintings
    ADD CONSTRAINT paintings_height_id_fkey FOREIGN KEY (height_id) REFERENCES public.height(id);


--
-- Name: paintings paintings_width_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: maemo
--

ALTER TABLE ONLY public.paintings
    ADD CONSTRAINT paintings_width_id_fkey FOREIGN KEY (width_id) REFERENCES public.width(id);


--
-- PostgreSQL database dump complete
--

\unrestrict psUgWCdIwuaff5NvKTLA0cxXOCCgdkMhU5ybgXEkH4oVaThVvM9go4JD9sNrKiJ

