// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309120203_DbChanges")]
    partial class DbChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cat")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id")
                        .IsUnique();

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Models.Height", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("cm")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("height", (string)null);
                });

            modelBuilder.Entity("Models.Paintings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("Heightid")
                        .HasColumnType("integer")
                        .HasColumnName("height_id");

                    b.Property<string>("Imagelink")
                        .HasColumnType("text")
                        .HasColumnName("image_link");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float?>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<bool>("Sold")
                        .HasColumnType("boolean")
                        .HasColumnName("sold");

                    b.Property<int?>("Widthid")
                        .HasColumnType("integer")
                        .HasColumnName("width_id");

                    b.HasKey("Id");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Heightid");

                    b.HasIndex("Widthid");

                    b.ToTable("paintings", (string)null);
                });

            modelBuilder.Entity("Models.Width", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("cm")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("width", (string)null);
                });

            modelBuilder.Entity("Models.Paintings", b =>
                {
                    b.HasOne("Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Height", "Height")
                        .WithMany()
                        .HasForeignKey("Heightid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Width", "Width")
                        .WithMany()
                        .HasForeignKey("Widthid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Height");

                    b.Navigation("Width");
                });
#pragma warning restore 612, 618
        }
    }
}
